### PR TITLE
Add Linux support

### PR DESCRIPTION
**Pull request by maxdevjs**
Check for Linux platform and set Bookmark path accordingly.

### CODE REVIEW

**Comment by bayleedev** [comment]
Thank you for the contribution! I'll take a look at this!

**Comment by bayleedev** [comment]
[this post](https://superuser.com/a/52431) suggests this is only sometimes right. I'd suggest we either need to make this account for both cases, or just have users overwrite the default setting that's currently allowed.

**Comment by maxdevjs** [comment]
Of course, and the user

- could use ```chromium```
- could use ```google-chrome-beta``` (even, if previously logged in in ```google-chrome```, seems that the beta uses the ```google-chrome``` profiles path) 
- could use ```google-chrome-stable```
- could use a ```Default n``` profile
- etc

Not sure, but the same may apply to OSX and possibly to Windows (I have one more PR ready to support Windows's "default case").

Could be a good start, perhaps and currently, to make aware users that it is possible to overwrite the default setting for edge cases?

**Comment by bayleedev** [comment]
Yeah that sounds great. [:

**Pull request merged**
